# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  producerapi:
    image: producerapi
    build:
      context: .
      dockerfile: Publisher/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5025:5025
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
